# 进程与多线程


import threading # 多线程开发模块
import time # 做一个延迟处理
def worker(delay):# 线程处理函数
    for num in range(50): # 循环执行线程功能
        time.sleep(delay) # 设置操作延迟
        print('【%s】线程执行计数：%s ' % (threading.current_thread().name, num))
def main(): # 主函数
    work_threads = [threading.Thread(target=worker, args=(1,), name=f'YootkThread - {item}')
                    for item in range(10)] # 创建10个线程对象
    for thread in work_threads: # 列表迭代
        thread.start()
if __name__ == '__main__':  # Python程序运行起点
    main() # 调用主函数


# PS E:\summer_study\python开发\programe\pythonProject> & D:/python_install_file/python.exe "e:/summer_study/python开发/programe/pythonProject/多进程编程/Processes and Multithreading.py"
# 【YootkThread - 0】线程执行计数：0 
# 【YootkThread - 2】线程执行计数：0 
# 【YootkThread - 1】线程执行计数：0
# 【YootkThread - 5】线程执行计数：0
# 【YootkThread - 8】线程执行计数：0
# 【YootkThread - 6】线程执行计数：0
# 【YootkThread - 3】线程执行计数：0
# 【YootkThread - 9】线程执行计数：0
# 【YootkThread - 7】线程执行计数：0
# 【YootkThread - 4】线程执行计数：0
# 【YootkThread - 0】线程执行计数：1 
# 【YootkThread - 2】线程执行计数：1 
# 【YootkThread - 1】线程执行计数：1
# 【YootkThread - 3】线程执行计数：1
# 【YootkThread - 5】线程执行计数：1
# 【YootkThread - 6】线程执行计数：1
# 【YootkThread - 8】线程执行计数：1
# 【YootkThread - 9】线程执行计数：1
# 【YootkThread - 7】线程执行计数：1
# 【YootkThread - 4】线程执行计数：1
# 【YootkThread - 0】线程执行计数：2 
# 【YootkThread - 1】线程执行计数：2 
# 【YootkThread - 2】线程执行计数：2
# 【YootkThread - 6】线程执行计数：2
# 【YootkThread - 5】线程执行计数：2
# 【YootkThread - 3】线程执行计数：2
# 【YootkThread - 4】线程执行计数：2
# 【YootkThread - 7】线程执行计数：2
# 【YootkThread - 8】线程执行计数：2
# 【YootkThread - 9】线程执行计数：2
# 【YootkThread - 0】线程执行计数：3 
# 【YootkThread - 2】线程执行计数：3 
# 【YootkThread - 1】线程执行计数：3
# 【YootkThread - 5】线程执行计数：3
# 【YootkThread - 6】线程执行计数：3
# 【YootkThread - 4】线程执行计数：3
# 【YootkThread - 3】线程执行计数：3
# 【YootkThread - 7】线程执行计数：3
# 【YootkThread - 8】线程执行计数：3
# 【YootkThread - 9】线程执行计数：3
# 【YootkThread - 0】线程执行计数：4 
# 【YootkThread - 1】线程执行计数：4 
# 【YootkThread - 2】线程执行计数：4
# 【YootkThread - 6】线程执行计数：4
# 【YootkThread - 5】线程执行计数：4
# 【YootkThread - 7】线程执行计数：4
# 【YootkThread - 3】线程执行计数：4
# 【YootkThread - 4】线程执行计数：4
# 【YootkThread - 9】线程执行计数：4
# 【YootkThread - 8】线程执行计数：4
# 【YootkThread - 0】线程执行计数：5 
# 【YootkThread - 2】线程执行计数：5 
# 【YootkThread - 1】线程执行计数：5
# 【YootkThread - 6】线程执行计数：5
# 【YootkThread - 7】线程执行计数：5
# 【YootkThread - 4】线程执行计数：5
# 【YootkThread - 5】线程执行计数：5
# 【YootkThread - 8】线程执行计数：5
# 【YootkThread - 3】线程执行计数：5
# 【YootkThread - 9】线程执行计数：5
# 【YootkThread - 1】线程执行计数：6 
# 【YootkThread - 0】线程执行计数：6 
# 【YootkThread - 2】线程执行计数：6
# 【YootkThread - 6】线程执行计数：6
# 【YootkThread - 7】线程执行计数：6
# 【YootkThread - 4】线程执行计数：6
# 【YootkThread - 5】线程执行计数：6
# 【YootkThread - 9】线程执行计数：6
# 【YootkThread - 3】线程执行计数：6
# 【YootkThread - 8】线程执行计数：6
# 【YootkThread - 0】线程执行计数：7 
# 【YootkThread - 1】线程执行计数：7 
# 【YootkThread - 2】线程执行计数：7
# 【YootkThread - 6】线程执行计数：7
# 【YootkThread - 7】线程执行计数：7
# 【YootkThread - 4】线程执行计数：7
# 【YootkThread - 3】线程执行计数：7
# 【YootkThread - 5】线程执行计数：7
# 【YootkThread - 9】线程执行计数：7
# 【YootkThread - 8】线程执行计数：7
# 【YootkThread - 0】线程执行计数：8 
# 【YootkThread - 2】线程执行计数：8 
# 【YootkThread - 6】线程执行计数：8
# 【YootkThread - 1】线程执行计数：8
# 【YootkThread - 7】线程执行计数：8
# 【YootkThread - 9】线程执行计数：8
# 【YootkThread - 5】线程执行计数：8
# 【YootkThread - 4】线程执行计数：8
# 【YootkThread - 8】线程执行计数：8
# 【YootkThread - 3】线程执行计数：8
# 【YootkThread - 0】线程执行计数：9 
# 【YootkThread - 6】线程执行计数：9 
# 【YootkThread - 2】线程执行计数：9
# 【YootkThread - 1】线程执行计数：9
# 【YootkThread - 9】线程执行计数：9
# 【YootkThread - 7】线程执行计数：9
# 【YootkThread - 5】线程执行计数：9
# 【YootkThread - 4】线程执行计数：9
# 【YootkThread - 8】线程执行计数：9
# 【YootkThread - 3】线程执行计数：9
# 【YootkThread - 0】线程执行计数：10 
# 【YootkThread - 2】线程执行计数：10 
# 【YootkThread - 6】线程执行计数：10
# 【YootkThread - 1】线程执行计数：10
# 【YootkThread - 7】线程执行计数：10
# 【YootkThread - 9】线程执行计数：10
# 【YootkThread - 5】线程执行计数：10
# 【YootkThread - 8】线程执行计数：10
# 【YootkThread - 4】线程执行计数：10
# 【YootkThread - 3】线程执行计数：10
# 【YootkThread - 0】线程执行计数：11 
# 【YootkThread - 6】线程执行计数：11 
# 【YootkThread - 2】线程执行计数：11
# 【YootkThread - 1】线程执行计数：11
# 【YootkThread - 9】线程执行计数：11
# 【YootkThread - 7】线程执行计数：11
# 【YootkThread - 5】线程执行计数：11
# 【YootkThread - 4】线程执行计数：11
# 【YootkThread - 8】线程执行计数：11
# 【YootkThread - 3】线程执行计数：11
# 【YootkThread - 0】线程执行计数：12 
# 【YootkThread - 6】线程执行计数：12 
# 【YootkThread - 2】线程执行计数：12
# 【YootkThread - 1】线程执行计数：12
# 【YootkThread - 9】线程执行计数：12
# 【YootkThread - 7】线程执行计数：12
# 【YootkThread - 5】线程执行计数：12
# 【YootkThread - 8】线程执行计数：12
# 【YootkThread - 4】线程执行计数：12
# 【YootkThread - 3】线程执行计数：12
# 【YootkThread - 0】线程执行计数：13 
# 【YootkThread - 2】线程执行计数：13 
# 【YootkThread - 9】线程执行计数：13
# 【YootkThread - 6】线程执行计数：13
# 【YootkThread - 1】线程执行计数：13
# 【YootkThread - 4】线程执行计数：13
# 【YootkThread - 5】线程执行计数：13
# 【YootkThread - 3】线程执行计数：13
# 【YootkThread - 7】线程执行计数：13
# 【YootkThread - 8】线程执行计数：13
# 【YootkThread - 0】线程执行计数：14 
# 【YootkThread - 2】线程执行计数：14 
# 【YootkThread - 1】线程执行计数：14
# 【YootkThread - 6】线程执行计数：14
# 【YootkThread - 9】线程执行计数：14
# 【YootkThread - 3】线程执行计数：14
# 【YootkThread - 5】线程执行计数：14
# 【YootkThread - 4】线程执行计数：14
# 【YootkThread - 8】线程执行计数：14
# 【YootkThread - 7】线程执行计数：14
# 【YootkThread - 0】线程执行计数：15 
# 【YootkThread - 1】线程执行计数：15 
# 【YootkThread - 2】线程执行计数：15
# 【YootkThread - 6】线程执行计数：15
# 【YootkThread - 9】线程执行计数：15
# 【YootkThread - 5】线程执行计数：15
# 【YootkThread - 3】线程执行计数：15
# 【YootkThread - 4】线程执行计数：15
# 【YootkThread - 8】线程执行计数：15
# 【YootkThread - 7】线程执行计数：15
# 【YootkThread - 0】线程执行计数：16 
# 【YootkThread - 2】线程执行计数：16 
# 【YootkThread - 1】线程执行计数：16
# 【YootkThread - 9】线程执行计数：16
# 【YootkThread - 6】线程执行计数：16
# 【YootkThread - 3】线程执行计数：16
# 【YootkThread - 5】线程执行计数：16
# 【YootkThread - 8】线程执行计数：16
# 【YootkThread - 4】线程执行计数：16
# 【YootkThread - 7】线程执行计数：16
# 【YootkThread - 0】线程执行计数：17 
# 【YootkThread - 1】线程执行计数：17 
# 【YootkThread - 2】线程执行计数：17
# 【YootkThread - 9】线程执行计数：17
# 【YootkThread - 6】线程执行计数：17
# 【YootkThread - 3】线程执行计数：17
# 【YootkThread - 8】线程执行计数：17
# 【YootkThread - 5】线程执行计数：17
# 【YootkThread - 7】线程执行计数：17
# 【YootkThread - 4】线程执行计数：17
# 【YootkThread - 1】线程执行计数：18 
# 【YootkThread - 0】线程执行计数：18 
# 【YootkThread - 6】线程执行计数：18
# 【YootkThread - 9】线程执行计数：18
# 【YootkThread - 2】线程执行计数：18
# 【YootkThread - 3】线程执行计数：18
# 【YootkThread - 8】线程执行计数：18
# 【YootkThread - 4】线程执行计数：18
# 【YootkThread - 5】线程执行计数：18
# 【YootkThread - 7】线程执行计数：18
# 【YootkThread - 9】线程执行计数：19 
# 【YootkThread - 6】线程执行计数：19 
# 【YootkThread - 1】线程执行计数：19
# 【YootkThread - 2】线程执行计数：19
# 【YootkThread - 0】线程执行计数：19
# 【YootkThread - 3】线程执行计数：19
# 【YootkThread - 5】线程执行计数：19
# 【YootkThread - 4】线程执行计数：19
# 【YootkThread - 8】线程执行计数：19
# 【YootkThread - 7】线程执行计数：19
# 【YootkThread - 9】线程执行计数：20 
# 【YootkThread - 1】线程执行计数：20 
# 【YootkThread - 6】线程执行计数：20
# 【YootkThread - 2】线程执行计数：20
# 【YootkThread - 0】线程执行计数：20
# 【YootkThread - 3】线程执行计数：20
# 【YootkThread - 5】线程执行计数：20
# 【YootkThread - 4】线程执行计数：20
# 【YootkThread - 7】线程执行计数：20
# 【YootkThread - 8】线程执行计数：20
# 【YootkThread - 1】线程执行计数：21 
# 【YootkThread - 9】线程执行计数：21 
# 【YootkThread - 2】线程执行计数：21
# 【YootkThread - 6】线程执行计数：21
# 【YootkThread - 3】线程执行计数：21
# 【YootkThread - 0】线程执行计数：21
# 【YootkThread - 4】线程执行计数：21
# 【YootkThread - 5】线程执行计数：21
# 【YootkThread - 8】线程执行计数：21
# 【YootkThread - 7】线程执行计数：21
# 【YootkThread - 1】线程执行计数：22 
# 【YootkThread - 6】线程执行计数：22 
# 【YootkThread - 2】线程执行计数：22
# 【YootkThread - 9】线程执行计数：22
# 【YootkThread - 0】线程执行计数：22
# 【YootkThread - 5】线程执行计数：22
# 【YootkThread - 3】线程执行计数：22
# 【YootkThread - 8】线程执行计数：22
# 【YootkThread - 4】线程执行计数：22
# 【YootkThread - 7】线程执行计数：22
# 【YootkThread - 1】线程执行计数：23 
# 【YootkThread - 6】线程执行计数：23 
# 【YootkThread - 9】线程执行计数：23
# 【YootkThread - 2】线程执行计数：23
# 【YootkThread - 3】线程执行计数：23
# 【YootkThread - 5】线程执行计数：23
# 【YootkThread - 0】线程执行计数：23
# 【YootkThread - 4】线程执行计数：23



